language: ruby
dist: trusty
sudo: false

env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chef/bin:/opt/chef/embedded/bin:/opt/chefdk/embedded/bin:$PATH"
  matrix:
  - COOKBOOK_PATH="cookbooks"
  - COOKBOOK_PATH="community-cookbooks"

addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk

before_script:
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: ./.test.sh
